version: '3.7'

services:
  web-dev:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - "/app/node_modules"
      - "./:/app"
    environment:
      - CHOKIDAR_USEPOLLING=true
  web-prod:
    container_name: my-app-prod
    restart: always
    build: .
    ports:
      - 3000:3000
      - 9229:9229